#! /bin/sh

bspc config border_width              1
bspc config window_gap                14

bspc config split_ratio               0.60
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config leaf_monocle              true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     true
bspc config auto_alternate            true
bspc config ignore_ewmh_focus         true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^2
bspc rule -a Chromium desktop=^3
bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a feh desktop=^9
bspc rule -a MPlayer floating=on
