theme = "heisenberg2"

[editor]
line-number = "absolute"
bufferline = "multiple"
text-width = 120
cursorline = true
mouse = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
newline = "¬" #"⏎"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
display-inlay-hints = true
snippets = true

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-indicator = "↪"
wrap-at-text-width = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-type", "file-encoding"]
center = ["diagnostics"]
right = ["selections", "primary-selection-length", "position-percentage", "position"]


[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
D = "delete_char_backward"
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"
