theme = "everforest_dark"

[editor]
cursorline = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["diagnostics"]
right = ["selections", "primary-selection-length", "file-type", "file-encoding", "position-percentage", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "⇥" # "→"
newline = "⮒" # "¬" #"⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
display-inlay-hints = true
snippets = true

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-indicator = "↪"
wrap-at-text-width = false

[keys.normal]
X = "extend_line_above"
D = "delete_char_backward"
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

[keys.select]
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"
