### MY PROGRAMS ###
# See https://wiki.hypr.land/Configuring/Keywords/
# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$lock = hyprlock

### AUTOSTART ###
exec-once = hyprctl plugin load /usr/lib64/hyprland/libhyprexpo.so
exec-once = hypridle & hyprsunset & ashell & swww-daemon & $terminal
exec-once = swww img ~/.background-image

