# https://wiki.hypr.land/Configuring/

# could use globing, but we want to ensure the correct order
source = ./hyprland.env.conf      # environment config
source = ./hyprland.monitors.conf # screen/monitor config
source = ./hyprland.programs.conf # var defs and program execs
source = ./hyprland.input.conf    # input devices and key bindings
source = ./hyprland.looks.conf    # general, decoration, animations
source = ./hyprland.rules.conf    # window and workspace rules
